var _tmr=_tmr||[];
(function(){function Eb(){return sa&&Fb&&ab?(bb=[Fb-sa,ab-sa,Ma?Ma-sa:null,Na?Na-sa:null].join("/"),Ma&&Na&&(Eb=function(){return bb}),bb):null}function n(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function N(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function Gb(a,b){try{if(a.nodeName.toLowerCase()===b.toLowerCase())return a;if(a.parentNode)return Gb(a.parentNode,b)}catch(c){q&&console.warn("[TopMailRu] Error#1.25",
c)}return null}function Hb(a,b){if(null===a.offsetParent||(0==a.offsetHeight||0==a.offsetWidth||0==a.clientHeight||0==a.clientWidth)||b&&(0==a.offsetLeft||0==a.offsetTop))return!1;if(void 0!==f.getComputedStyle){var c=f.getComputedStyle(a,null);return"none"!==c.display&&"hidden"!==c.visibility}return!0}function I(a,b){for(var c=0,d=b.length;c<d;c++)if(b[c]==a)return!0;return!1}function P(a){var b=typeof a;return!("number"===b||"boolean"===b||"string"===b||a.nodeType||a===a.window)}function aa(a){return"[object Array]"===
Object.prototype.toString.call(a)}function ba(){var a=arguments,b=a[0]||{},c=!1,d=1,g=a.length,h,e,k,r,u;"boolean"===typeof b&&(c=b,b=a[d++]||{});for(P(b)||(b={});d<g;d++)if(null!=(h=a[d]))for(e in h)k=b[e],r=h[e],b!==r&&(c&&r&&(P(r)||(u=aa(r)))?(u?(u=!1,k=k&&aa(k)?k:[]):k=k&&P(k)?k:{},b[e]=ba(c,k,r)):void 0!==r&&(b[e]=r));return b}function Ib(a,b,c){if(!a)return null;var d=a.match(b),g=2<arguments.length?c:0;return d&&d.length>g?d[g]:null}function Jb(a){return(""+a).replace(/[\/\^\$\*\+\?\.\|\(\)\[\]\{\}\\]/g,
"\\$&")}function cb(a){return Ib(a.host,/^(?:w{3}.)?(.*)$/,1)||""}function qc(a,b,c){a=cb(a);b=(b&&0<b?b:URL_HELPER__MASK_LEVEL)-1;var d=1;a=a.replace(RegExp("^.*(?:\\.((?:[^\\.]+\\.){"+b+"}[^\\.]+$))"),"$1");if(d=a.match(/\./g))d=d.length;a="(?:^|\\.{"+(b-d+1)+"})"+Jb(a)+"$";return RegExp(c?"^((?!"+a+").)*$":a)}function db(a){var b;if(aa(a)){b=[];for(var c=0,d=a.length;c<d;c++)b.push(db(a[c]));return b}b=a instanceof RegExp?a:RegExp("^"+Jb(a)+"$");return b.test(cb(E))?null:b}function Kb(a){var b=
"";try{var c=new Uint8Array(a);f.crypto.getRandomValues(c);for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(g){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}function w(){return(new Date).getTime()}function C(a,b){var c={data:b,raw:a,url:eb(a)},d;if(!rc||"function"!==typeof navigator.sendBeacon)d=!1;else{c.dataSplitter=";";var g=fb(c.data,c.dataSplitter);try{d=!0===navigator.sendBeacon(c.url,g)}catch(h){d=!1}}d||(void 0===b?(c.dataSplitter=";",c.open=sc,c.connect=
tc,c.startListen=uc,c.stopListen=vc,c.open(c),c.connect(c)):("function"===typeof f.XMLHttpRequest?(c.dataSplitter=";",c.open=wc,c.connect=xc,c.startListen=yc,c.stopListen=zc,c.open(c),c.connect(c),d=!0):d=!1,d||Ac(c)))}function Ac(a){var b=l.createElement("iframe"),c=l.createElement("div");c.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");c.appendChild(b);l.body.appendChild(c);try{var d=b.contentWindow.document,
g=d.createElement("div"),h;for(h in a.data)if(a.data.hasOwnProperty(h)){var e=a.data[h],k=typeof e;if("string"===k||"number"===k){var r=d.createElement("input");r.setAttribute("type","hidden");r.setAttribute("name",h);r.value=e;g.appendChild(r)}}var u=d.createElement("form");u.setAttribute("action",a.url);u.setAttribute("method",Lb);u.setAttribute("enctype",Mb);u.appendChild(g);var f=d.createElement("div");f.appendChild(u);d.body.appendChild(f);var m=function(){try{N(b,"load",m),l.body.removeChild(c)}catch(a){q&&
console.warn("[TopMailRu] Error#1.2",a)}};n(b,"load",m);u.submit()}catch(s){q&&console.warn("[TopMailRu] Error#1.3",s)}}function wc(a){a._connection=new f.XMLHttpRequest}function xc(a){a._connection.open(Lb,a.url);a._connection.setRequestHeader("Content-Type",Mb);a._connection.send(fb(a.data,a.dataSplitter))}function yc(a){n(a._connection,"load",a._onload);n(a._connection,"error",a._onerror)}function zc(a){N(a._connection,"load",a._onload);N(a._connection,"error",a._onerror)}function sc(a){a._connection=
new Image}function tc(a){a._connection.src=a.url+fb(a.data,a.dataSplitter)}function uc(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function vc(a){a._connection.onload=null;a._connection.onerror=null}function fb(a,b){var c=b||";",d="",g;for(g in a)if(a.hasOwnProperty(g)){var h=a[g],e=typeof h;if("string"===e||"number"===e)d+=c+escape(g)+"="+escape(h)}return d}function eb(a){a="string"===typeof a?a:"/";return"https://top-fwz1.mail.ru"+("/"===a.substring(0,1)?"":"/")+a}function Q(a){return(a=
l.cookie.match(RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function ia(a,b,c){c=c||{};var d=c.expires;"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var g in c)if((b=c[g])||0===b)a+="; "+g,!0!==b&&(a+="="+b);l.cookie=a}function gb(a,b){var c=b||{};c.expires=-1;ia(a,"",c)}function Bc(){var a="tmr"+(""+Math.random()).slice(2);
try{return V=f.localStorage||null,V.setItem(a,a),V.removeItem(a),!0}catch(b){return V=null,q&&console.warn("[TopMailRu] Error#1.4",b),!1}}function za(a){try{return V.getItem(a)}catch(b){q&&console.warn("[TopMailRu] Error#1.5",b)}return null}function Aa(a,b){try{V.setItem(a,b)}catch(c){q&&console.warn("[TopMailRu] Error#1.6",c)}}function Cc(){if(!W)return null;for(var a=E.hostname.split(".").reverse(),b,c=1,d=a.length;c<d;c++){b=a[0];for(var g=1;g<=c;g++)b=a[g]+"."+b;var g=""+w(),h={domain:b,path:"/",
expires:3E5};try{ia("tmr_tcdhn",g,h);var e=Q("tmr_tcdhn");gb("tmr_tcdhn",h);if(e===g)return b}catch(k){q&&console.warn("[TopMailRu] Error#1.8",k)}}return null}function Nb(a,b){W&&ia(a,b,hb);ja&&Aa(a,b)}function ib(a,b,c){var d=l.createElement("script");d.type="text/javascript";d.async=!0;b&&(d.onload=b);c&&(d.onerror=c);d.src=a;document.body.appendChild(d)}function Ob(a){var b=";e="+escape("detect");C(J(a,K,!1,!1)+b)}function Pb(a,b){if(a.length&&null!==b.ecom_data){var c=xa(b.ecom_data),c=c?(""+
c).substring(1,c.length-1):"";if(!(4096<c.length||-1===c.search(/\S/))){var d=jb("_m",b.ecom_method),g=jb("_t",b.ecom_type),h=jb("_jst",Qb()),c="{"+c+d+g+h+"}";C(J({id:a[0]},Dc,!1,!0)+(";ids="+escape(a.join()))+(";e="+escape(c)))}}}function jb(a,b){var c=',"'+a+'":';if(!b||!b.length)return c+"[]";try{return c+'["'+b.join('","')+'"]'}catch(d){}return c+"false"}function Ec(){var a=Q(Rb);if(null===a)return null;a=a.split("|");if(3!==a.length)return null;var b=a[2],b=w()-b;return 0>b||b>Sb?null:{id:a[0],
version:a[1]}}function Tb(a){kb=!0;a.length&&ib(eb("/js/dyn-goal-config.js?ids="+a.join(",")))}function m(){}function ka(a){a&&"object"===typeof a&&(!ca&&"id"in a)&&(ca=a.id)}function ta(a){return!Oa?void 0:Oa[a]}function Fc(a){return(a=ta(a))&&Pa?a-Pa:void 0}function Ub(){if(Oa){for(var a=0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<b.length;c++){var d=ta(b[c]);if(0<d&&(d<a||0==a))a=d}return a?a:void 0}}function X(a,
b){var c=1<arguments.length?b:ca;return a&&"object"===typeof a&&("id"in a&&a.id||c)}function Vb(a,b,c,d){var g=parseInt(a,10);return isNaN(g)||""+g!==""+a||g<b||g>c?d||0===d?d:null:g}function Wb(a,b){if("URL"in window){var c=b;try{c=new URL(a)}catch(d){return b}return c?a:b}return a||b}function J(a,b,c,d){ja&&Aa(ua,++R);var g="id"in a?a.id:ca,h=Wb(a.url,E.href),e=Wb(a.referrer,l.referrer),k="title"in a?a.title:l.title,r;r=lb;null===r&&(r=Gc());r=null!==r?r?1:0:null;var u="userid"in a?a.userid:S||
0===S?S:void 0,m=da?da:void 0,n;n=la&&a.bfCache;var s="pageView"===a.type&&a.timespent,p=[];ca&&g!==ca&&p.push("sec");"dataLayer"in f&&p.push("dl");F&&p.push(["ecom"].concat(F).join("-"));var Ba=Hc();Ba&&Ba.length&&p.push(["jst"].concat(Ba).join("-"));n&&p.push("bfc");T&&s&&p.push("ts");f.top!==f&&p.push("frame");n=p.join(",");s=(new Date).getTimezoneOffset();p="";if(f.Intl)try{p=f.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(Ic){q&&console.warn("[TopMailRu] Error#1.1",Ic)}Ba=s+"/"+
p;s=Xb;s=null!==s?s:Ec();p=Eb();a.start=Ub();b=b+"?_="+Math.random()+(g?";id="+escape(g):"")+(h?";u="+escape(h):"")+(e?";r="+escape(e):"")+(a.start?";st="+escape(a.start):"");g=Vb(a.gender,1,2);b+=null!==g?";gender="+g:"";g=Vb(a.age,1,127);d=b+(null!==g?";age="+g:"")+("pid"in a?";pid="+escape(a.pid):"")+(void 0!==u?";userid="+escape(u):"")+(void 0!==m?";uparams="+escape(xa(m)):"")+(d&&k?";title="+encodeURIComponent(k):"");k=";s="+Jc+";vp=";m=u=0;l.documentElement&&(l.documentElement.clientWidth||
l.documentElement.clientHeight)?(u=l.documentElement.clientWidth,m=l.documentElement.clientHeight):"number"==typeof f.innerWidth&&(u=f.innerWidth,m=f.innerHeight);d=d+(k+(""+u+"*"+m)+";touch="+Kc+";hds="+Lc)+";sid="+mb+";ver="+Mc+";tz="+encodeURIComponent(Ba);if(c){if(!Oa||!nb)c="";else{c=[];c.push(nb.type);c.push(nb.redirectCount);c.push(Pa);for(k=0;k<Yb.length;k++)c.push(Fc(Yb[k]));c=c.join("/")}c=";nt="+c}else c="";c=d+c+(p?";ct="+p:"")+(Qa?";gl="+Qa:"")+("device"in a?";device="+escape(a.device):
"")+";ni=";if(!M||!M.connection)p="";else{p=M.connection;d=[];for(u=0;u<Zb.length;u++){k=p[Zb[u]];if(void 0!==k)switch(k){case !0:k=1;break;case !1:k=0;break;default:k=(""+k).replace(/\//g,"_")}d.push(k)}p=d.join("/")}return c+p+("params"in a?";params="+escape(xa(a.params)):"")+(null!==r?";detect="+r:"")+(W||ja?";lvid="+escape([va,w(),R,ma].join(":")):"")+(n?";opts="+escape(n):"")+(s?";flocid="+escape(s.id)+";flocv="+escape(s.version):"")+($b&&Ca?";fpid="+Ca:"")+("version"in a?";appver="+escape(a.version):
"")+(na.support?";visible="+na.getValue():"")+";js=13"}function ob(a){a=";e="+escape(a);for(var b=0;b<D.length;b++)C(J(D[b],K,!1,!0)+a)}function Nc(){lb=!0;ac(1);if(!pb&&!Da){Da=!0;for(var a=0;a<D.length;a++)Ob(D[a])}}function Oc(){ac(0);lb=!1}function Gc(){var a=Q(bc);if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=w()-b;if(0>b||b>cc)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function ac(a){var b=w();a=[a,b].join("|");ia(bc,a,{path:"/",expires:cc})}function Pc(){var a=
0;Ra&&(a=w()-Ra);Qc||(x.dcl3=setTimeout(function(){ob("DCL/3")},Math.max(3E3-a,0)))}function Rc(){var a=0;Sa&&(a=w()-Sa);Sc||(x.pvt2=setTimeout(function(){ob("PVT/2")},Math.max(2E3-a,0)));Tc||(x.pvt15=setTimeout(function(){ob("PVT/15")},Math.max(15E3-a,0)))}function dc(){qb||setInterval(function(){_tmr.beat()},6E4)}function Uc(a,b,c,d){if(!b||!d||d===rb&&b===rb&&c===rb)return null;b={goal:Vc+b,value:c||0,params:{product_id:d}};a&&(b.id=a);return b}function Ta(){Ra=w();l.addEventListener?(N(l,"DOMContentLoaded",
Ta),_tmr.onready()):l.attachEvent&&"complete"===l.readyState&&(N(l,"readystatechange",Ta),_tmr.onready());ec()}function sb(a){Sa=w();if(la){if(a.persisted){Ea=Fa=Ua=0;tb=ub=!1;T&&y.launch();a=vb;vb=[];for(var b=0,c=a.length;b<c;b++)_tmr.callbackOnReady(a[b]);a=Va;Va={};for(b in a)_tmr.pageView(a[b]);dc()}}else N(f,"load",sb);_tmr.onready();_tmr.onload()}function Ga(){la||(N(f,"unload",Ga),N(f,"beforeunload",Ga));_tmr.unload()}function ec(){T&&y.launch();if(Wc&&fc){window.addEventListener("message",
function(a){var c=null;try{if(c=a.data,P(c)||(c=Wa(c)),"LOAD_BUTTONS_SCRIPT"===c.type){var d;var g=document.referrer;a=null;var h=(""+c.lang).toLowerCase(),e;b:{for(var c=0,k=wb.length;c<k;c++)if(wb[c]===h){e=!0;break b}e=!1}e||(h=wb[0]);try{a=(new URL(g)).host}catch(r){}d=a&&Xc.test(a)?"https://"+a+"/top_constructor/buttons_"+h+".js":eb("/js/dyn-goal-wizard-"+h+".js");ib(d)}}catch(f){}});if(window.opener)try{window.opener.postMessage({type:"READY"},document.referrer)}catch(a){}kb||(Xa.push.apply(Xa,
Ha),Tb(Ha))}}if("[object Array]"===Object.prototype.toString.call(_tmr)){var Fb=(new Date).getTime(),ab=null,Ma=null,Na=null,sa=null,bb=null,K="/tracker",Dc="/datalayer",f=window,M=navigator,l=document,E=location,Y="string"===typeof E.hostname?E.hostname:"",Ia=-1!=Y.search(/(^|\.)odnoklassniki\.ru$/)||-1!=Y.search(/(^|\.)ok\.ru$/),gc=-1!=Y.search(/(^|\.)vk\.com$/);Y.search(/(^|\.)mail\.ru$/);var Yc=-1!=Y.search(/(^|\.)lamoda\.ru$/),Zc=-1!=Y.search(/(^|\.)kommersant\.ru$/);Y.search(/(^|\.)top\.mail\.ru$/);
Y.search(/(^|\.)dzen\.ru$/);var hc="string"===typeof E.search&&-1!=E.search.search(/[?&]rb_clickid=/),q="string"===typeof E.search&&-1!=E.search.search(/[?&]tmr_debug=1(?:&|$)/),rc=!1,qb=Ia||gc||Yc||Zc,Sc=!hc,Tc=Ia,Qc=!hc,pb=!1,T=f.performance&&"visibilityState"in l,$c=[36383],ad=!(Ia||gc),Wc=!0,$b=!0,ic=f.JSON&&f.JSON.stringify&&f.JSON.parse,la="onpageshow"in f&&"onpagehide"in f,fc="URL"in f,xa=ic?f.JSON.stringify.bind(f.JSON):function(a){return""},Wa=ic?f.JSON.parse.bind(f.JSON):function(a){return{}},
wb=["ru","en"],Xc=/^(ads\d+\.my\.com)$/,Lb="POST",Mb="application/x-www-form-urlencoded",W=!(0===E.hostname.search(/^(\d+.)+\d+$/g)||-1!==E.hostname.search(/:/g)),V=null,ja=Bc(),hb={domain:Cc(),path:"/",expires:287712E5};(function(){var a;if(a=l.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)","g"))){for(var b=[],c,d=0,g=a.length;d<g;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&b.push(c.slice(1));a=b}else a=null;if(a){d=0;for(g=a.length;d<g;d++)b=a[d][0],gb(b,hb)}})();var Da=!1,
lb=null,cc=864E5,bc="tmr_detect",bd=function(){function a(a,b){for(var c=a.length,e,k,f=0;f<b;f++)k=Math.floor(Math.random()*c),e=a[f],a[f]=a[k],a[k]=e;return a.slice(0,b)}function b(b,g){var h=l.createElement("div"),e=String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,100,118,101,114,116,66,108,111,99,107,32,98,45,114,98,32,98,97,110,110,101,114,95,50,52,48,32,112,45,116,97,114,103,101,116,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,
48,48,120,50,53,48,109,32,112,117,98,95,55,50,56,120,57,48,32,114,98,95,98,111,100,121,32,114,98,45,102,108,111,97,116,105,110,103,32,114,98,45,115,108,111,116,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,116,101,120,116,45,97,100,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,98,97,110,110,101,114,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,65,100,32,116,101,120,116,97,100,32,116,101,
120,116,65,100,115,32,116,101,120,116,97,100,115,32,116,103,98,45,98,97,110,110,101,114,32,116,114,103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107).split(" "),e=a(e,c);h.setAttribute("class",e.join(" "));h.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");h.setAttribute("id","trg-b-banners-1");h.setAttribute("data-view","SlotView.mimic");this.bait=l.body.appendChild(h);this.bait.offsetParent;
this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=b||null;this.fnNegative=g||null;var k=this;setTimeout(function(){k._checkBait.call(k)},1)}var c=7;b.prototype._checkBait=function(){if(Da)this._stop();else{var a=null!==l.body.getAttribute("abp")||!Hb(this.bait,!0);(!0===a||10<=++this.loopNumber)&&this._stop();var b;if(a&&this.fnPositive)try{b=this.fnPositive,b()}catch(c){q&&console.warn("[TopMailRu] Error#1.9",
c)}else if(!a&&10>this.loopNumber){var e=this;setTimeout(function(){e._checkBait.call(e)},50*this.loopNumber)}else try{b=this.fnNegative,b()}catch(k){q&&console.warn("[TopMailRu] Error#1.10",k)}}};b.prototype._stop=function(){try{l.body.removeChild(this.bait)}catch(a){q&&console.warn("[TopMailRu] Error#1.11",a)}};return function(a,c){new b(a,c)}}(),F=null,jc="ecommerce",B="dataLayer",ea=null,xb=!1,Ya=[],cd=[36383,2540645,3171181,3074137,2057653],dd=[],yb;(function(){function a(a,b){for(var c=0,d=
b.length;c<d;c++)-1===a.indexOf(b[c])&&a.push(b[c])}function b(b,c,d){for(var g={ecom_method:[],ecom_type:[],ecom_data:{events:[]}},h=0,k=b.length;h<k;h++){var e=n[b[h]];if(e){a(g.ecom_method,[b[h]]);for(var f=0,u=e.length;f<u;f++)for(var r=0,l=d.length;r<l;r++){var p=e[f][d[r]];if(p)for(var t=0,m=c.length;t<m;t++)if(-1!==e[f].type.indexOf(c[t])){a(g.ecom_type,[c[t]]);a(g.ecom_data.events,p);break}}}}return g}function c(a,b,c){if(!a||!c||!(b in n))return null;for(var d,g=0,h=n[b].length;g<h;g++)if(d=
n[b][g],c in d&&-1!==d[c].indexOf(a))return{ecom_method:[b],ecom_type:d.type.slice(),ecom_data:{}};return null}function d(a){for(var d=[],e,f,l=0,ed=a.length;l<ed;l++)if(f=a[l]){e=null;try{if(f.ecommerce)e=g(f)||h(f);else if(null===f.ecommerce)e=null;else if(f.event){var m={event:f.event,ecommerce:{}};e=g(m)||h(m)}else if("event"===f[0]){var oa=f[1],n=f[2],z=c(oa,r,s);z&&(z.ecom_data[oa]=n);e=z}else if(f.event===jc)a:{for(var Ja=b([k],[u],[p]),zb=0,t=Ja.ecom_data.events.length;zb<t;zb++)if(!f.hasOwnProperty(Ja.ecom_data.events[zb])){e=
null;break a}delete Ja.ecom_data.events;Ja.ecom_data[jc]=f;e=Ja}}catch(w){q&&console.warn("[TopMailRu] Error#1.23",w),e=null}e&&(d.push(e),Ya.push(e))}if(d.length){a=0;for(e=d.length;a<e;a++)Pb(Za,d[a]);F||(F=[0,0,B]);F[0]+=d.length;e=a=0;for(l=d.length;e<l;e++)a+=xa(d[e].ecom_data).length;F[1]+=a}}function g(a){var b,d;for(d in a.ecommerce)if(a.ecommerce.hasOwnProperty(d)&&(b=c(d,k,l))){if(a.event&&(d=c(a.event,k,m)))for(var g=0,e=b.ecom_type.length;g<e;g++)-1===d.ecom_type.indexOf(b.ecom_type[g])&&
(b.ecom_type.splice(g,1),e--,g--);b.ecom_data=a.ecommerce;return b}return null}function h(a){var b=a.event,d=c(b,k,m);d&&(d.ecom_data[b]=a.ecommerce);return d}function e(a){if((a=f[a])&&"function"===typeof a.push)d(a),ea=a.push,a.push=function(){var a=ea.apply(this,arguments);d([].slice.call(arguments,0));return a}}var k="push",r="gtag",u="gse",l="inner",m="outer",s="external",p="required",n={};n[r]=[{type:["gee"],external:"add checkout checkout_option checkout_progress click detail promo_click remove select_content set_checkout_option view_refund".split(" ")},
{type:["ga4"],external:"earn_virtual_currency join_group level_end level_start level_up post_score select_content spend_virtual_currency tutorial_begin tutorial_complete unlock_achievement ad_impression login search share sign_up add_payment_info add_shipping_info add_to_wishlist generate_lead select_item select_promotion view_cart view_item_list".split(" ")},{type:["gee","ga4"],external:"add_to_cart begin_checkout purchase refund remove_from_cart view_item view_promotion".split(" ")}];n[k]=[{type:[u],
required:["transactionId","transactionTotal"]},{type:["ga4"],outer:b([r],["ga4"],[s]).ecom_data.events},{type:["gee"],inner:"click checkout checkout_option impressions promoClick promoView refund".split(" "),outer:"addToCart checkout checkoutOption productClick productDetail ProductImpressions promotionClick promotionView removeFromCart transactionPush".split(" ")},{type:["ym","gee"],inner:["add","detail","purchase","remove"]},{type:["mt"],outer:["mt_order","mt_refund"]}];yb=function(a){if(!(a===
B&&ea)){a!==B&&(Ya=[]);var b=f[B];b&&"function"===typeof b.push&&ea&&(b.push=ea,ea=null);e(a);xb=!0}}})();var Qb=function(){var a=[{id:"gtag",globalVars:["google_tag_manager"]},{id:"ga",globalVars:["GoogleAnalyticsObject"]},{id:"ym",globalVars:["Ya",{re:"yaCounter\\d+"}]},{id:"vk",globalVars:["VK"]},{id:"vk",globalVars:["vkAsyncInit"]}],b={};return function(){var c;try{c=Object.keys(f).join(",")}catch(d){c=null}for(var g=[],h,e=0,k=a.length;e<k;e++){h=b[a[e].id];if(void 0===h)a:{h=a[e].globalVars;
for(var r=c,u=0,l=h.length;u<l;u++){var m=h[u];if("string"===typeof m&&!(m in f)||"string"===typeof m.re&&(r&&-1===r.search(RegExp("($|,)"+m.re+"(,|^)","m"))||1===l)){h=!1;break a}}h=!0}h&&(b[a[e].id]=!0,I(a[e].id,g)||g.push(a[e].id))}return g}}(),Hc=Qb,Sb=864E5,Rb="tmr_floc",Xb=null;(function(a){try{l.interestCohort&&"function"===typeof l.interestCohort&&l.interestCohort().then(function(a){Xb={id:a.id,version:a.version};a=[a.id,a.version];var b=w();a=a.concat(b).join("|");ia(Rb,a,{path:"/",expires:Sb})},
function(){})}catch(b){}})();var Ab=!1,Qa=null,Ka=null,Bb=!1,kc;(function(){function a(a){try{var c=a.state;Ka=c in e?e[c]:h;Bb=c===g;Ab&&b(Bb)}catch(d){}}function b(a){try{a?(M[d].getCurrentPosition(c),f||(f=M[d].watchPosition(c))):(f&&M[d].clearWatch(f),c(null))}catch(b){}}function c(a){if(a)try{var b=a.coords,b=[b.latitude,b.longitude,b.accuracy,b.altitude,b.altitudeAccuracy,b.heading,b.speed];a=0;for(var c=b.length;a<c;a++)"number"!==typeof b[a]&&(b[a]="");b.splice(0,0,Ka);Qa=b.join("/")}catch(d){}else Qa=
Ka}var d="geolocation",g="granted",h="u",e={denied:"d"};e[g]="g";e.prompt="p";var f=null;(function(){Ka=h;c(null);try{d in M?M.permissions&&M.permissions.query({name:d}).then(function(b){a(b);b.onchange=function(){a(b)}}):Ka="n"}catch(b){}})();kc=b})();var na={support:!1},na=function(){function a(){g(e)}function b(){g(e,s)}function c(a){a.persisted&&(p[e]=null,p[k]=null,g(e,q))}function d(){return r?!l[r]:null}function g(a,b){var c=w(),g="undefined"===typeof b?d():b;if(null===p[a])p[a]={ts:c,state:g,
total:0};else{var e=p[a];if(e.state!==g&&!(e.state===s&&g!==q)){var f=c-e.ts,k=e.state;e.ts=c;e.state=g;f<h||(k===q?(e.total+=f,y&&y(c,f)):k===x&&v&&v(c,f))}}}var h=5,e="auto",k="user",r=null,m=null,q=!0,x=!1,s=null;"hidden"in l?(r="hidden",m="visibilitychange"):"mozHidden"in l?(r="mozHidden",m="mozvisibilitychange"):"webkitHidden"in l?(r="webkitHidden",m="webkitvisibilitychange"):"msHidden"in l&&(r="msHidden",m="msvisibilitychange");var p={};p[e]=null;var y=p[k]=null,v=null;return{support:!!r,auto:function(d,
g){y=d||null;v=g||null;r&&(a(),n(l,m,a));la?(n(f,"pageshow",c),n(f,"pagehide",b)):(n(f,"beforeunload",b),n(f,"unload",b))},set:function(a){g(k,!!a)},getLog:function(){var a=w(),b={},c,d;for(d in p)c=p[d],b[d]=c?c.total:0,c&&c.state&&(b[d]+=a-c.ts);return b},getValue:d}}();na.auto();var lc={enabled:!1};if(fc){var mc=function(){var a="checkbox color date datetime-local email file month number password radio range search tel text time url week".split(" ");return{analyze:function(b){if(!b)return null;
for(var c=[].slice.apply(b.elements),d=[],g=[],f=0,e=c.length;f<e;f++){var k;a:switch(k=c[f],k.tagName.toLowerCase()){case "button":k=!1;break a;case "input":var l=k.type.toLowerCase();if(l&&-1===a.indexOf(l)){k=!1;break a}default:k=Hb(k,!1)&&k.name&&!1===k.disabled}k&&(d.push(c[f].name),g.push(c[f].type))}return{node:b,inputsName:d.length?d:null,inputsType:g.length?g:null}},getFormByInput:function(a){if(!a)return null;a=a.form||a.getAttribute("form");return"string"===typeof a?document.getElementById(a)||
null:a instanceof HTMLElement?a:null}}}(),lc=function(){function a(a){a=a||f.event;var c=(a.which||a.keyCode)===N;if("which"in a&&a.which===D||"button"in a&&a.button&D||c){a:{a=a.target||a.srcElement;for(var c=0,d=e.length;c<d;c++){var l;b:{l=a;for(var z=e[c],p=0,n=z.types.length;p<n;p++){var t;c:{var s=l;t=z.types[p];var A=null;if(t.filter.tagName)for(var L=0,v=t.filter.tagName.length;L<v&&!(A=Gb(s,t.filter.tagName[L]));L++);else A=s;if(A){if(t.filter.attr)for(s in s=void 0,t.filter.attr)if(t.filter.attr.hasOwnProperty(s)&&
(L=t.filter.attr[s],v=A[s],!0===L&&!v||!1===L&&v||aa(L)&&-1===L.indexOf(v))){t=null;break c}t={source:A,type:t.type,detail:A.tagName}}else t=null}if(t){t.category=z.category;l=t;break b}}l=null}if(l){a=l;break a}}a=null}if(a){if(a.category===g){try{a.data=new URL(a.source.href)}catch(C){}if(!a.data)return}else if(a.category===h){if(a.data=mc.analyze(mc.getFormByInput(a.source)),!a.data)return}else return;c=J;if(c.enabled&&c.modes){d=0;for(l=c.modes.length;d<l;d++)if(z=a,p=c.modes[d],z.category===
p.mode)if(z.category===g||z.category===h){if(p=p.categories,z.data){n=void 0;c:{n=0;for(t=p.length;n<t;n++){for(var A=z,s=p[n],L={category:z.category},v=[],U=0,E=s.types.length;U<E;U++){var qa=s.types[U],K=ba({type:s.category},L),F=y in qa,I;w in qa?I=b(A,qa,K,w):F&&(I=ba({source:A.source,data:A.data,detail:qa.type},K));if(I&&(!F||!b(A,qa,K,y)))if(v.push(I),(qa.rule&x)!==x)break}if(A=v.length?v:null){n=A;break c}}n=null}if(n){z=0;for(p=n.length;z<p;z++)c:{t=n[z];A={type:"sendEvent",category:"_"+t.category,
action:t.detail};if(t.category===g&&(t.type===k||t.type===m)){if(A.label=t.data.href,!A.label)break c}else if(t.category===u&&(A.label=t.data.node.action,!A.label))break c;_tmr.push(A)}}}}else q&&console.warn("[TopMailRu] Error#1.24","Not found tracking for type",z.type)}}}}function b(a,b,d,g){var e=!1,f=b[g];if(aa(f)){var h=b[g+"Rule"]||C;g=(h&s)===s;for(var h=(h&p)===p,k=0,l=f.length;k<l&&!(e=c(a,f[k]),g&&e);k++)if(h&&!e)return null}else e=c(a,f);return!e?null:ba({source:a.source,data:a.data,detail:b.type},
d)}function c(a,b){var c=b.rule||C,g=(c&s)===s,c=(c&p)===p,e=!1,f;for(f in b)if(b.hasOwnProperty(f)&&"rule"!==f){var e=b[f],h;switch(f){case "domain":h=cb(a.data);break;case "fileExtension":h=Ib(a.data.pathname,/.\.([^\.]+)$/,1)||"";break;default:h=a.data[f]}e=!0===e?!!(aa(h)?h.length:h):!1===e?!(aa(h)?h.length:h):d(h,e);if(g&&e)break;else if(c&&!e)return!1}return e}function d(a,b){var c=a;if(c)if(aa(c)){if(!c.length)return!1}else c=[c];else return!1;var d=b,e=C;if(P(d)&&!aa(d)){if(!aa(d.value))return!1;
e=d.rule||e;d=d.value}a:{for(var g=(e&v)===v,f=(e&s)===s,e=(e&p)===p,h=!1,k=0,l=d.length;k<l;k++){var m=d[k];if(m){var n="string"===typeof m;n&&!g&&(m=m.toLowerCase());var r=m instanceof RegExp;if(n||r){var h=!0,q;b:{q=c;for(var u=g,w=0,y=q.length;w<y;w++){var x=u?q[w]:q[w].toLowerCase();if(r&&m.test(x)||n&&m===x){q=!0;break b}}q=!1}if(f&&q){c=!0;break a}else if(e&&!q){c=!1;break a}}}}c=f?!1:e?h?!0:!1:void 0}return c}var g="click",h="submit",e=[{category:h,types:[{type:"button",filter:{tagName:["input",
"button"],attr:{type:["submit","image"]}}}]},{category:g,types:[{type:"a",filter:{tagName:["a"],attr:{href:!0}}}]}],k="file",m="resource",u="submit",w="filter",y="stop",s=1,p=2,v=4,x=8,C=s,J={enabled:!0,modes:[{mode:h,categories:[{category:u,types:[{type:"lead",filter:[{inputsName:["phone"],inputsType:["tel"],rule:s},{inputsName:["email"],inputsType:["email"],rule:s}],filterRule:p,stop:{inputsName:{value:["password"]}}},{type:"form",filter:{inputsName:!0}}]}]},{mode:g,categories:[{category:"contact",
types:[{type:"email",filter:{protocol:["mailto:"]}},{type:"phone",filter:{protocol:["tel:"]}}]},{category:k,types:[{type:"file",filter:{fileExtension:"7z bz2 gz apk iso cab dmg msi rar tar zip exe txt doc docx ppt pptx xls xlsx csv pdf psd rtf ods djvu eps 3gp aac ac3 avi flac flv divx midi mka mkv mp3 mp4 mpeg mpg mov ogg vob wav webm wma wmf wmv torrent".split(" ")}}]},{category:m,types:[{type:"outgoing",rule:x,stop:{domain:[qc(E.host,3,!1)],href:[/password/]}},{type:"messenger",filter:{domain:db("vk.me t.me telegram.me telegram.im web.telegram.org m.me web.whatsapp.com api.whatsapp.com chat.whatsapp.com wa.me".split(" "))},
stop:{href:[/password/]}},{type:"social",filter:{domain:db("vk.com vkontakte.ru m.vk.com vk.ru ok.ru m.ok.ru odnoklassniki.ru facebook.com m.facebook.com fb.com twitter.com linkedin.com instagram.com tiktok.com youtube.com youtu.be m.youtube.com".split(" "))},stop:{href:[/password/]}}]}]}]},D=1,N=13;return{enabled:!0,start:function(){n(l,"click",a);n(l,"keypress",a)}}}();ad&&lc.start()}var y=function(){function a(){b(null)}function b(a){g();a?(W=a===U,pa=a):pa=$&&null!==W?W?U:da:l.visibilityState;
a=B();for(var b in fa)y(b,a)}function c(){if(!1!==Q){N(f,A,ka);ka=null;f.clearInterval(ma);na=ma=null;N(l,L,ea);ea=null;$&&(N(f,Y,ha),N(f,ba,ia),ia=ha=null);h(!0);for(var a in Z){var b=a,c=Z[b];c&&(c=c.key,P(b),oa(),delete Z[b],z(null,c))}G=null;ga=[];wa=[];H={};Z={};fa={};Q=!1}}function d(a,b,c){var d=a+"_"+b;if(d in H)return!1;var e=w(),g=B(),f=M(d,e,mb);b=H[d]={id:a||null,name:b,key:f,canUseInBackground:!!c,startTS:e,updateTS:g,timespent:{}};if(a)if(wa.push(d),d=b.canUseInBackground,b=fa[a]){if(c=
b.isActive,!c&&(e=G&&I(a,G)))if(c=pa===U||d)b.updateTS=g,b.isActive=!0}else e=G&&I(a,G),c=pa===U||d,fa[a]={isActive:e&&c,updateTS:g,timespent:{}};else ga.push(d);return!0}function g(a,b){var c,d;2>arguments.length?(c=wa.concat(ga),d=S):(c=[a+"_"+b],d=X);e(c,d)}function h(a,b,c){var d=!1,g=[],f=[];2>arguments.length?(g=wa.slice(),(d=!!arguments[0])&&(g=g.concat(ga))):(d=a+"_"+b,-1!==wa.indexOf(d)?g=[d]:-1!==ga.indexOf(d)&&(c?g=[d]:f=[d]));e(g,ca);e(f,X)}function e(a,b){var c=B(),d=[],e,g,f;e=0;for(g=
a.length;e<g;e++)f=a[e],-1!==wa.indexOf(f)?k(f,b,c):-1!==ga.indexOf(f)&&d.push(f);e=0;for(g=d.length;e<g;e++)f=d[e],k(f,b,c);if(b===S&&(V=c,V-Q>=sa)){for(var h in H)q(h);for(h in Z)if(c=h,d=Z[c])P(c),z(c,d.key);Q=V}}function k(a,b,c){var d=H[a];if(d&&!1!==d.updateTS)if(d.timespent[pa]=(d.timespent[pa]||0)+(c-(d.updateTS||V)),-1!==ga.indexOf(a)&&D(null,c),b===ca)d.updateTS=!1,q(a);else if(b===t){d.updateTS=c;var e;a:{if(b=H[a])for(e in b.timespent)if(b.timespent[e]>ra){e=!1;break a}e=!0}e?(m(a),oa()):
q(a)}else d.updateTS=b===S?null:c,m(a),oa()}function m(a,b,c){var d=H[a];if(!d)return null;var e=b||d.key;b=O[e];O[e]={uid:a,name:d.name,counterID:c||d.id||G,canUseInBackground:d.canUseInBackground,isActive:!1!==d.updateTS,startTime:d.startTS,timespent:{}};a=O[e].timespent;var d=d.timespent,g;for(g in d)a[g]=d[g];if(c&&(c=fa[c]))if(e=O[e]){e.common={};e=e.common;c=c.timespent;for(var f in c)e[f]=c[f]}return b||null}function q(a){var b=H[a];b&&(m(a),v(a,b.key))}function v(a,b){var c=O[b];if(c)if(aa(c.counterID)){var d=
O[b];if(d){var c=d.counterID,e=[],g,f,h,k;if(c){h=0;for(k=c.length;h<k;h++){f=c[h];g=M(b,f);e.push(g);f=m(a||d.uid,g,f);var l=void 0;f&&(l=O[g],R(l.timespent,f.timespent),f.common&&(l.common=l.common||{},R(l.common,f.common)))}}delete O[b];oa();if(a&&a in H)if(d.isActive){s(a);h=0;for(k=c.length;h<k;h++)if(d=fa[c[h]])for(var n in d.timespent)d.timespent[n]=0}else p(a);h=0;for(k=e.length;h<k;h++)x(e[h])}}else if(n=O[b])(c=a&&a in H)&&!n.isActive&&p(a),e=x(b),c&&(e&&n.isActive)&&s(a)}function x(a){var b;
if(b=O[a]){var c=T(b.timespent);if(!1===b.canUseInBackground&&b.isActive&&0===c.fg)b=null;else{c=[b.name,b.startTime,b.canUseInBackground?1:0,c.fg,c.bg];if(b.common){var d=T(b.common);(d.fg||d.bg)&&c.push(d.fg,d.bg)}b={id:b.counterID,msg:c.join("/")}}}else b=!1;if(!b)return!1;c=";e="+escape("TS:"+b.msg);C(J({id:b.id},K,!1,!1)+c);delete O[a];oa();return!0}function s(a){if(a=H[a])for(var b in a.timespent)a.timespent[b]=0}function p(a){if(a in H){var b;-1!==(b=ga.indexOf(a))&&ga.splice(b,1);if(-1!==
(b=wa.indexOf(a)))if(wa.splice(b,1),b=H[a].id){var c=fa[b];if(c){var d=c.isActive;d&&F(c,B());d=E(b,a);d||(c.isActive=!1)}}delete H[a]}}function y(a,b){var c=fa[a];if(c){var d=G&&I(a,G),e=E(a);c.isActive=d&&e;c.updateTS=b}}function D(a,b){if(a){var c=fa[a];c&&(c.isActive?F(c,B()):c.updateTS=b)}else for(c in fa)D(c,b)}function E(a,b){for(var c in H)if(c!==b&&H[c].id===a&&(pa===U||H[c].canUseInBackground))return!0;return!1}function F(a,b){a&&(a.timespent[pa]=(a.timespent[pa]||0)+(b-a.updateTS),a.updateTS=
b)}function M(a){return[].join.call(arguments,"_")}function R(a,b){for(var c in b)a[c]=(a[c]||0)+(b[c]||0)}function T(a){var b=a[U]||0,c=0,d;for(d in a)d!==U&&(c+=a[d]);return{fg:b,bg:c}}function B(){return Math.floor(f.performance.now())}function oa(){if(ja){var a={};a[ua]=O;a[va]=ya;Aa(ta,xa(a)||"")}}function P(a){var b=Z[a];b&&(ya[b.key]={uid:a,name:b.name,counterID:b.id,value:b.value})}function z(a,b){if(ya[b]){var c;if(c=ya[b])if(0===c.value)c=null;else{var d=[c.name,c.value].join("/");c={id:c.counterID,
msg:d}}else c=!1;c&&(d=";e="+escape("TS:"+c.msg),C(J({id:c.id},K,!1,!1)+d));!1!==c&&(delete ya[b],oa());if(c&&a&&(c=Z[a]))c.value=0}}var X=1,S=2,t=4,ca=8,A=la?"pagehide":"unload",L="visibilitychange";"mozHidden"in l?L="mozvisibilitychange":"webkitHidden"in l?L="webkitvisibilitychange":"msHidden"in l&&(L="msvisibilitychange");var Y="focus",ba="blur";"onfocusin"in l&&(Y="focusin",ba="focusout");var U="visible",da="hidden",qa=["0"],$=!1,ra=100,sa=12E4,Q=!1,V=!1,G=null,ga=[],wa=[],H={},pa,W=null,ma,na,
ea,ha,ia,ka,ta="tmr_tslog",ua="activity",va="count",O={},Z={},ya={},fa={};return{init:function(){if(ja){var a=Wa(za(ta)||"{}");O=a[ua]||{};ya=a[va]||{}}for(var b in O)v(null,b);for(b in ya)z(null,b)},launch:function(){!1===Q&&(Q=B(),V=B(),pa=$&&null!==W?W?U:da:l.visibilityState,ka=c.bind(f),n(f,A,ka),na=a.bind(f),ma=f.setInterval(na,1E4),ea=b.bind(f,null),n(l,L,ea),$&&(ha=b.bind(f,U),ia=b.bind(f,da),n(f,Y,ha),n(f,ba,ia)))},enable:function(a){if(G){if(I(a,G))return;e(ga,t)}else{for(var b=0,c=qa.length;b<
c;b++)d(null,qa[b],!1);G=[]}G.push(a);y(a,B())},disable:function(a){if(G){var b;a:{b=0;for(var c=G.length;b<c;b++)if(G[b]==a)break a;b=-1}if(-1!==b&&(e(ga,t),G.splice(b,1),b=B(),a=fa[a]))a.isActive=!1,a.updateTS=b}},startActivity:d,updateActivity:g,stopActivity:h,incCount:function(a,b){var c=a+"_"+b,d;if(!(d=Z[c]))if(c in Z)d=Z[c];else{d=w();var e=M(b,d,mb);d=Z[c]={id:a,name:b,key:e,startTS:d,value:0}}d&&d.id===a&&(d.value++,P(c),oa())},defaultID:function(){return G?G[0]:void 0}}}(),kb=!1,Ca=null;
$b&&function(){function a(){var a=za(g);if(a)try{(a=Wa(a))&&(Ca=a.fpid||null)}catch(b){}c()}function b(){c()}function c(){Aa(d,xa({fpid:Ca,ts:w()}))}var d="tmr_trgfpid",g="rb_sync_id";(function(){var c=ja?za(d):null;if(c)try{if(c=Wa(c))if(Ca=c.fpid||null,864E5>w()-c.ts)return}catch(e){}ib("https://privacy-cs.mail.ru/static/sync-loader.js",a,b)})()}();var Mc="60.5.1",Ua=0,Fa=0,mb=Kb(16),S=null,da=null,Ea=0,ua="tmr_reqNum",R=null;W&&(R=Q(ua)||null,null!==R&&gb(ua,hb));ja&&null===R&&(R=za(ua)||null);
R=null===R?0:parseInt(R,10);ja&&Aa(ua,R);var ma=(W?Q("tmr_lvid"):null)||(ja?za("tmr_lvid"):null),va=(W?Q("tmr_lvidTS"):null)||(ja?za("tmr_lvidTS"):null);if(null===ma||-1===ma.search(/^[0-9a-fA-F]+$/))ma=Kb(32);Nb("tmr_lvid",ma);if(null===va||-1===va.search(/^\d+$/))va=""+w();Nb("tmr_lvidTS",va);var ca=0,D=[],Ha=[],$a=[],Za=[],Xa=[],Va={},Kc="ontouchstart"in f||1<(M.maxTouchPoints||M.msMaxTouchPoints)?"1":"0",Lc=f.devicePixelRatio||0,Jc=function(){var a=f.screen;return a?a.width+"*"+a.height:""}(),
nc=f.performance||f.mozPerformance||f.msPerformance||f.webkitPerformance||{},Oa=nc.timing||{},nb=nc.navigation||{},Yb="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),Pa=ta("navigationStart"),fd=ta("domContentLoadedEventStart"),gd=
ta("loadEventStart"),sa=Pa,Zb="downlink downlinkMax effectiveType rtt saveData type".split(" "),$,Cb;$=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||ca,g=c.title||null,f,e=Cb(b,{params:c.required,fn:c.fn});if(e.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<e.missed.length&&e.missed.slice(0,-1).join(", ")+" and "||"")+e.missed.slice(-1)+" in "+a);else{var k=Cb(b,{params:c.optional,fn:c.fn});f=[].concat(e.values).concat(k.values);e=[].concat(e.missed).concat(k.missed);
c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?f.push("value: "+b):e.push("value"));c=f.length?"{ "+f.join(", ")+" }":"";f=e.length?"("+(1<e.length?e.slice(0,-1).join(", ")+" and "+e.slice(-1)+" are":e.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(g||a)+" "+c+" "+f):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};Cb=function(a,b){var c=[],d=[],g,f,e;if(b.params)for(g in b.params)if(b.params.hasOwnProperty(g)&&
!1!==b.params[g])if(f=g in a&&a[g],!0!==b.params[g]&&(f=f||b.params[g]),f)try{e=b.fn?b.fn:null,c.push(g+': "'+(e?e(g,f):f)+'"')}catch(k){console.warn("[TopMailRu] Error#1.16",k)}else d&&d.push(g);return{values:c,missed:d}};var x={},Sa=null,Ra=null,vb=[];m.prototype.callbackOnReady=function(a){q&&$("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&(a.callback.call(a.context||null),la&&vb.push(a))};m.prototype.pageView=function(a){ka(a);a:if(a&&"object"===
typeof a&&a.id){5>Ha.length&&!I(a.id,Ha)&&(Ha.push(a.id),!1!==a.beat&&$a.push(a.id),D.push(a),Da&&Ob(a));la&&(Va[a.id]=ba(!0,{},a),Va[a.id].bfCache=!0);"detectBlocker"in a&&!a.detectBlocker&&(pb=!0);var b="string"===typeof a.ecommerce,c=b&&-1!==a.ecommerce.search(/\S/);if(5>Za.length&&!I(a.id,Za)&&(!0===a.ecommerce||b&&!c||b&&c||!1!==a.ecommerce&&!b&&(I(a.id,cd)||!I(a.id,dd)))){Za.push(a.id);if(b&&c){if(xb&&(yb(a.ecommerce),B!==a.ecommerce)){B=a.ecommerce;F&&(F=[0,0,B]);break a}B=a.ecommerce;F&&(F=
[0,0,B])}b=[a.id];if(xb)for(var c=0,d=Ya.length;c<d;c++)Pb(b,Ya[c])}a.timespent=T&&(a.timespent||I(a.id,$c)&&!1!==a.timespent);T&&(a.timespent?y.enable(a.id):y.disable(a.id));Ab||(Ab=!0===a.geolocation||a.timespent&&!1!==a.geolocation)&&kc(Bb);kb&&!I(a.id,Xa)&&(Xa.push(a.id),Tb([a.id]))}q&&$("pageView",a,{title:"Page view",optional:{url:E.href}});X(a)&&(C(J(a,"/counter",!1,!0)),Fa=w())};m.prototype.reachGoal=function(a){ka(a);q&&$("reachGoal",a,{title:"Reach goal",value:!0,required:{goal:!0}});if(X(a)&&
"goal"in a&&a.goal){var b="value"in a&&a.value?parseInt(a.value)||"":"";C(J(a,K,!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal)))}};var rb="VALUE";m.prototype.itemView=function(a){q&&$("itemView",a,{title:"Item view",optional:{list:!0,pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(X(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",f=a.totalvalue||0,h=Uc(a.id,d,f,c);h&&this.reachGoal(h);(new Image).src="https://ad.mail.ru/retarget/?counter="+(a.id||ca)+
"&list="+b+"&productid="+c+"&pagetype="+d+"&totalvalue="+f+"&_="+Math.random();b="IV:"+f+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");C(J(a,K,!1,!0)+(";e="+escape(b)))}};var Vc="vk_ecom_";m.prototype.sendEvent=function(a){ka(a);q&&$("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substring(0,300).replace(/;/g," ")}});if(X(a)&&"category"in a&&a.category&&"action"in a&&a.action){var b=
(""+a.category).substring(0,300),c=(""+a.action).substring(0,300),d="label"in a&&a.label?(""+a.label).substring(0,300):"",b="CE:"+("value"in a&&a.value?parseInt(a.value)||"":"")+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");C(J(a,K,!1,!0)+(";e="+escape(b)))}};m.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==b&&"string"!==b?q&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):
(S=a,q&&console.info("[TopMailRu]: Global user ID = "+S))}};m.prototype.getUserID=function(){return S||0===S?S:void 0};m.prototype.deleteUserID=function(){S=null;q&&console.info("[TopMailRu]: Reset global user ID to null")};m.prototype.setUserParams=function(a){if(null===a||!1===a||void 0===a)this.deleteUserParams();else if(P(a)){try{da=ba(!0,{},a)}catch(b){q&&console.warn("[TopMailRu] Error#1.22","Invalid user params in setUserParams");return}q&&console.info("[TopMailRu]: Global user params = "+
xa(da))}else q&&console.warn("[TopMailRu] Error#1.21","Invalid user params in setUserParams")};m.prototype.getUserParams=function(){var a=da?da:void 0;return a?ba(!0,{},a):void 0};m.prototype.deleteUserParams=function(){da=null;q&&console.info("[TopMailRu]: Reset global user params to null")};m.prototype.getClientID=function(){var a=ma;return a||0===a?a:void 0};m.prototype._MT_event=function(a,b,c){ka(a);q&&$(b,a,{title:c});X(a)&&C(J(a,K,!1,!0)+(";e="+escape("MT:/"+b)))};m.prototype.miniAppEvent=
function(a){this._MT_event(a,"miniAppEvent","VK Mini App Event")};var Db=function(a,b){if(T){var c=y.defaultID();X(a,c)&&(!P(a)||!("activity"in a&&a.activity)?q&&console.warn("[TopMailRu] Error#1.27","Invalid startActivity command: ID of activity is required"):y.startActivity(a.id||c,""+a.activity,null===b?!!a.canUseInBackground:b))}};m.prototype.startTimespent=function(a){Db(a,null)};m.prototype.startForegroundTimespent=function(a){Db(a,!1)};m.prototype.startAnytimeTimespent=function(a){Db(a,!0)};
m.prototype.updateTimespent=function(a){if(T){var b=y.defaultID();X(a,b)&&(!P(a)||!("activity"in a&&a.activity)?y.updateActivity():"number"===typeof a.activity||"string"===typeof a.activity?y.updateActivity(a.id||b,""+a.activity):q&&console.warn("[TopMailRu] Error#1.28","Invalid updateActivity command: ID of activity should be number or string"))}};m.prototype.stopTimespent=function(a){if(T){var b=y.defaultID();X(a,b)&&(!P(a)||!("activity"in a&&a.activity)?y.stopActivity(!1):"number"===typeof a.activity||
"string"===typeof a.activity?y.stopActivity(a.id||b,""+a.activity,!1):q&&console.warn("[TopMailRu] Error#1.29","Invalid stopActivity command: ID of activity should be number or string"))}};m.prototype.incrementEventTimespent=function(a){if(T){var b=y.defaultID();X(a,b)&&(!a||!("activity"in a&&a.activity)?q&&console.warn("[TopMailRu] Error#1.31","Invalid incrementEventTimespent command: ID of countable activity is required"):y.incCount(a.id||b,""+a.activity))}};m.prototype.processEvent=function(a,
b){if(a&&"object"===typeof a)if("type"in a){if("onready"===a.type){if(b&&0>b)return;this.callbackOnReady(a)}else if(b&&0<b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "setUserParams":"params"in a&&this.setUserParams(a.params);break;case "deleteUserParams":this.deleteUserParams();
break;case "miniAppEvent":this.miniAppEvent(a);break;case "startTimespent":this.startTimespent(a);break;case "startForegroundTimespent":this.startForegroundTimespent(a);break;case "startAnytimeTimespent":this.startAnytimeTimespent(a);break;case "updateTimespent":this.updateTimespent(a);break;case "stopTimespent":this.stopTimespent(a);break;case "incrementEventTimespent":this.incrementEventTimespent(a)}}else q&&console.warn("[TopMailRu] Error#1.19","Unspecified type of push event");else q&&console.warn("[TopMailRu] Error#1.18",
"Invalid push event")};m.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var oc=!1;m.prototype.onready=function(){oc||(oc=!0,!pb&&!Da&&bd(Nc,Oc),yb(B),Pc())};var ub=!1;m.prototype.onload=function(){if(!ub){ub=!0;Ea=w();if(!Ia&&0<D.length){for(var a=";e="+escape("RT/load")+";et="+Ea,b=0;b<D.length;b++)C(J(D[b],K,!0,!0)+a);Fa=Ea}Rc()}};m.prototype.beat=function(){var a;if(!qb&&Ua){var b=w();if(!(12E4<b-Ua)){if(12E4<b-Fa){a=";e="+escape("RT/resend")+
";et="+Ea;for(var c=0;c<D.length;c++)!1!==D[c].beat&&C(J(D[c],K,!1,!0)+a)}else 0<$a.length&&(a=";e="+escape("RT/beat")+";ids="+escape($a.join()),C(J({id:$a[0]},K,!1,!0)+a));Fa=b}}};var tb=!1;m.prototype.unload=function(){if(!tb){tb=!0;if(!Ia){var a;a=(a=Ub())?w()-a:void 0;a=";e="+escape("RT/unload")+";et="+w()+(a?";pvt="+escape(a):"");if(na.support){var b=na.getLog();a+=";vtauto="+b.auto}for(b=0;b<D.length;b++)C(J(D[b],K,!0,!0)+a)}la&&(x.dcl3&&(clearTimeout(x.dcl3),delete x.dcl3),x.pvt2&&(clearTimeout(x.pvt2),
delete x.pvt2),x.pvt15&&(clearTimeout(x.pvt15),delete x.pvt15),x.beat&&(clearInterval(x.beat),delete x.beat))}};m.prototype.activity=function(a){Ua=w()};var ha=_tmr;_tmr=new m;T&&y.init();for(var v=0,La=ha.length,ra;v<La;v++)(ra=ha[v])&&"object"===typeof ra&&ka(ra);ab=(new Date).getTime();v=0;for(La=ha.length;v<La;v++)ra=ha[v],_tmr.processEvent(ra,1);Ma=(new Date).getTime();v=0;for(La=ha.length;v<La;v++)ra=ha[v],_tmr.processEvent(ra,-1);"complete"===l.readyState||"loading"!==l.readyState&&!l.documentElement.doScroll?
(Ra=fd,_tmr.onready(),ec()):l.addEventListener?n(l,"DOMContentLoaded",Ta):l.attachEvent&&n(l,"readystatechange",Ta);"complete"===l.readyState?(Sa=gd,_tmr.onload()):la?n(f,"pageshow",sb):n(f,"load",sb);la?n(f,"pagehide",Ga):(n(f,"unload",Ga),n(f,"beforeunload",Ga));dc();if(!qb)try{for(var pc="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),hd=function(a){n(l,a,function(){_tmr.activity(a)})},v=0;v<pc.length;v++)hd(pc[v]);n(f,"scroll",function(){_tmr.activity("scallback")})}catch(id){q&&
console.warn("[TopMailRu] Error#1.20",id)}Na=(new Date).getTime()}})();
